### ISSUE TITLE
Improve password hashing

### ISSUE THREAD

**Issue by kpcyrd** [Luzifer/cloudkeys-go#14]
The `password-salt` setting mentioned in the readme seemed odd so I digged into the source to figure out how this is used:

https://github.com/Luzifer/cloudkeys-go/blob/f55273499d222af801b854995f77607f4c285b2b/register.go#L18

There are a couple of issues here:

## 1) Constant salt
There is a fixed salt for all users. This causes the following problems:

## 1.1) Duplicate hashes
If two users use the same (low quality) password, both of them get the same password hash. In extension to this:

## 1.2) Cracking complexity is O(n) instead of O(n^m)
Since there's no user specific parameter for the KDF, you can load the database into a datastructure like this:
```json
{
    "abchash1": ["alice", "bob"],
    "defhash2": ["charlie"]
}
```
Next, you would calculate the password hash for a password and then lookup if anybody/who uses that password. This allows you to crack all users at once instead of having to test a password for individual hashes.

## 1.3) Cachable internal state
This is somewhat theoretical (explanation follows), but given two users sharing the same prefix in their password (but not the exact same password), you can cache the state of the hash function. Given `AAA[...]AA1` and `AAA[...]AA2` you can compute the internal state of the sha1 function after the As and then just do the computation the difference after that, ending up in 3 blocks instead of 4. One would need to be extremly lucky for this to work, given the block size for sha1 is 512 bits and the salt plus the password would need to be longer than that. The prefix also needs to align with the sha1 block size. Given the salt is >= 512 bits this would be practical.

## 2) Low difficulty
sha1 and other hash functions are designed to be as fast as possible. For password hashing you usually want the function to be as slow as bearable (without DoSing yourself).

## Conclusion
For password hashing it's [generally recommended][0] to use a password based key derivation function like [bcrypt] or [scrypt] that have solutions (individual salts, configurable difficulty) for all of these problems built in.

[0]: https://codahale.com/how-to-safely-store-a-password/
[bcrypt]: https://godoc.org/golang.org/x/crypto/bcrypt
[scrypt]: https://godoc.org/golang.org/x/crypto/scrypt

**Comment by Luzifer** [comment]
Thanks for taking your time to report this issue!

Though this only affects the login password, not the master password I understand this is something to be addressed in case someone gets their hands on the user database. That's why I opened a PR (#15).

Can you please take a look at the changes made over there (especially commit d64fee60c88222835c9c1358b3475d662c9fc368)?
